### ISSUE TITLE
Cookie lifetime

### ISSUE THREAD

**Issue by fruel** [franzliedke/auth-fluxbb#10]
When logging in though this driver the FluxBB cookie has a static lifetime of 30min (or 2 weeks if remember == true).
This lifetime is never updated if the user interacts with the page. (= the browser deletes the cookie 30min after the login regardless if the user is idle or not)

When logging in directly in FluxBB the cookie has a lifetime of 0. ("until the end of the browser session")

Could you add an option to create a real session cookie instead of a 30min-cookie or an option to enable the refreshing of the cookie lifetime? (like laravel does with its session cookie - the 30 minutes are reset on each request)

**Comment by franzliedke** [comment]
Cheers, good idea. I'll take a look and implement that soon.

**Comment by franzliedke** [comment]
Can you check out my [latest commit](https://github.com/franzliedke/auth-fluxbb/commit/d6dd2562d3048e3d66e8ad7e46854a76d27073ac)? It's not in any release right now, so you'll have to require this library using `@dev`.

**Comment by fruel** [comment]
Looks good. Works for me.

Thanks.

**Comment by franzliedke** [comment]
Awesome! I just released [v1.0.6](https://github.com/franzliedke/auth-fluxbb/releases/tag/v1.0.6), which includes this fix.

**Comment by franzliedke** [comment]
I had fixed this, but introduced #11 with that change. I'll have to find another fix for this issue.

**Comment by franzliedke** [comment]
Okay, finally fixed properly in the just-releated [v1.0.7](https://github.com/franzliedke/auth-fluxbb/releases/tag/v1.0.7).
