### ISSUE TITLE
Logging in through Laravel doesn't login forum

### ISSUE THREAD

**Issue by sdousley** [franzliedke/auth-fluxbb#11]
Hi

I have a site that I am trying to integrate with fluxbb using this connector (and Laravel 4.2).

When I login on the site, it seems to work perfectly fine, and Auth::User() returns the fluxbb user.  However, wehn I then browse to the forums, it doesn't show as logged in at all, and I have to login again.  Oddly, however, logging out from the main site, does log out of the forums, and vice versa.

Logging in through the forums also works and then shows the site as logged in.

The way that I am doing the login is using Auth::attempt($credentials)  where $credentials is an array of inputs.

Do i need to do something else with teh response from this for the forums to realise that the user has logged in this way?

If you need an example URL, I can PM/Email you a link to it.

**Comment by DanielWarnaar** [comment]
- 1,
  I also have this

**Comment by franzliedke** [comment]
Thanks for the heads-up, I'll try to reproduce this.

Do any of you know when this started to happen?

**Comment by sdousley** [comment]
in addition to this, I have found that when using

Auth::attempt($credentials, true)    // Remember login

it DOES log the forum in

**Comment by franzliedke** [comment]
Ah, I assumed that it might have to do something with [my latest changes](https://github.com/franzliedke/auth-fluxbb/commit/d6dd2562d3048e3d66e8ad7e46854a76d27073ac) in that area.

Could you check whether reverting to v1.0.5 fixes this for you?

**Comment by sdousley** [comment]
seems like it might do,  just downgraded to 1.0.5, and it works perfectly now. :)

**Comment by sdousley** [comment]
I just checked by upgrading to 1.0.6, and "undoing" that commit manually, and it works again after that, so it's most definitely something there that has caused this to happen :)

**Comment by sdousley** [comment]
oops, clicked wrong button to close issue

**Comment by bvangraafeiland** [comment]
Encountering the same issue, downgrading to 1.0.5 for the time being.

**Comment by franzliedke** [comment]
Fixed on master, but now I'll have to fix #10 again.

**Comment by franzliedke** [comment]
Okay, folks, update to [v1.0.7](https://github.com/franzliedke/auth-fluxbb/releases/tag/v1.0.7) and you should all be happy again.
