### ISSUE TITLE
Take online timeout setting into account

### ISSUE THREAD

**Issue by franzliedke** [franzliedke/auth-fluxbb#12]
We currently let the cookies expire after 1800 seconds, which is the FluxBB standard setting for the online timeout.

That is configurable, though, and since the FluxBB login script [takes this into account](https://github.com/fluxbb/fluxbb/blob/c180901486b78efa94b3a7c9d9618b329be190e9/login.php#L81), this library should also.

This will require reading the FluxBB config (either from database or cache).

**Comment by bvangraafeiland** [comment]
This is something I'd very much like to see as well. Are you planning on implementing it yourself soon? Otherwise I'll pick it up, I don't think it's a lot of work.

**Comment by franzliedke** [comment]
Working on it right now.

**Comment by franzliedke** [comment]
Okay, I implemented this in master. Can you please test whether this works for you?
