### ISSUE TITLE
Support for password reminders

### ISSUE THREAD

**Issue by bvangraafeiland** [franzliedke/auth-fluxbb#13]
For my current project, it's desirable to have a "forgot password" link on the main site, however this is currently not supported using Laravel's Password facade. I would suggest either having this User class extending Eloquent, or also implementing RemindableInterface (you can just use the trait for the email method).

Then, all that needs to be done is a custom implementation of ReminderRepositoryInterface, and I think just extending DatabaseReminderRepository and overriding a couple of methods should be sufficient there, the major difference being that FluxBB doesn't use a separate table for reminders but puts them in the users table instead.

I would be glad to implement this myself, but just checking here whether it wasn't already on the list.

**Comment by franzliedke** [comment]
This sounds like a nice idea. It would be awesome if you could implement this.

**Comment by bvangraafeiland** [comment]
Alright, cool. Do you have a preference for either extending Eloquent's model or implementing RemindableInterface? From what I can see, the User model already behaves much like Eloquent.

**Comment by franzliedke** [comment]
Please avoid extending Eloquent if possible.

**Comment by bvangraafeiland** [comment]
Will do. Now, as I was working on this, I realized there are two ways to handle the password reset: the forum way of generating and sending a new password to the user, or the laravel way of presenting a form to choose a new password. Do you have a preference for either? (in the last case, nothing else really needs to change other than your User implementing RemindableInterface)

**Comment by franzliedke** [comment]
Hmm, not sure, I would think that it should be the FluxBB way. If that's much easier, though, you may as well go the other route.

**Comment by bvangraafeiland** [comment]
Well yeah, the short way is literally adding 2 lines of code. However, I don't mind doing the full implementation (was kinda halfway there when I realized it could be done faster)

**Comment by franzliedke** [comment]
This is now released in [v1.0.8](https://github.com/franzliedke/auth-fluxbb/releases/tag/v1.0.8).
