### ISSUE TITLE
Add "Recent Posts" models

### ISSUE THREAD

**Issue by sdousley** [franzliedke/auth-fluxbb#15]
As requested here: http://fluxbb.org/forums/viewtopic.php?pid=56559#p56559 please could some models be added to this to allow for getting the last X posts from a given forum ID.

Thanks in advance.

Steve

**Comment by franzliedke** [comment]
Okay, I've decided I do not really want to implement and maintain this here. 

However, I've created [a gist](https://gist.github.com/franzliedke/37f35777956516cb9149) that should help get you started. Very simple right now; if you have some suggestions, I will gladly add more stuff to it.

**Comment by sdousley** [comment]
Hi Franz

Thanks for the Gist.  I was thinking of writing something along these lines myself, but thought I would ask on the forums, and when you said you would implement it here, I must admit that I was rather surprised since it seems to be something that aims to achieve a seperate goal than "Auth".

I shall take this gist, and implement it into my app.:)
