### ISSUE TITLE
Laravel 4.1 support

### ISSUE THREAD

**Issue by shauno** [franzliedke/auth-fluxbb#2]
Hi
Is there any support for Laravel 4.1 planned? I am keen to try FluxBB, but only if I can integrate my existing users smoothly.
Thanks

**Comment by franzliedke** [comment]
Hi,

I'll update my composer.json later tonight and test whether it works. Thanks for the heads-up and a happy new year too you!

**Comment by modbase** [comment]
Any update on this? Thanks

**Comment by franzliedke** [comment]
Whoops, sorry. Today's the day, I promise. =)

**Comment by franzliedke** [comment]
Actually, try now. I just updated the `composer.json`, it might just work that way.

**Comment by shauno** [comment]
I moved onto a custom solution a couple weeks ago, and don't have a test install to check this now.

If @modbase is happy to test this for you, that would be best. Otherwise, feel free to close this issue if you are confident your change solves the problem.

**Comment by franzliedke** [comment]
Sorry @shauno for taking so long - apparently that made you use something else. I understand completely. If you ever consider using FluxBB again, please don't let this stop you. =)

@modbase Does this work for you?

**Comment by shauno** [comment]
No stress @franzliedke, I don't think I would have gone with FluxBB for this particular project anyway :)

**Comment by franzliedke** [comment]
I pushed out v1.0.1. I'm pretty confident this works. =)
