### ISSUE TITLE
How to make auth-fluxbb work under Laravel 3?

### ISSUE THREAD

**Issue by pmache** [franzliedke/auth-fluxbb#3]
Hey.

My website works under laravel 3, and I really appreaciate any help of getting this auth to work with my installation of flux with rest of my site.

This would work with L3? If no, how to adapt it to L3?

**Comment by franzliedke** [comment]
Well, that's a tough one. You could add this package using the Composer bundle for Laravel 3. When that is done, we'd still need to add a bundle start file and then write a custom [auth driver](https://github.com/laravel/laravel/blob/3.0/laravel/auth/drivers/driver.php) for Laravel 3. We won't be able to use the current one, it might be possible to build upon that, though...

**Comment by franzliedke** [comment]
I'm sorry, I've decided that adding support for Laravel 3 does not have very high priority for me, so I probably wouldn't get to it anyway. If you're able to create an auth driver for L3, feel free to send a pull request. =)
